---
# tasks file for ansible-role-dns

# update system
- name: update system
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: deinstall systemd-resolved
  ansible.builtin.apt:
    state: absent
    name: systemd-resolved

# update system
- name: install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present

- name: block config dnsmasq
  notify: restart dnsmasq
  block:
    # conf dnsmasq
    - name: apply dnsmasq / global conf
      ansible.builtin.copy:
        src: dnsmasq.conf
        dest: /etc/dnsmasq.conf
        owner: root
        mode: '0644'
        
    - name: apply dnsmasq / DNS conf
      ansible.builtin.copy:
        src: dnsmasq-dns.conf
        dest: /etc/dnsmasq-dns.conf
        owner: root
        mode: '0644'

    # add 
    - name: Template file for 
      ansible.builtin.template:
        src: dnsmasq-hosts-auto.conf.j2
        dest: /etc/dnsmasq-hosts-auto.conf
        owner: root
        mode: '0644'